version: "3"
services:
  mysql:
    container_name: mysql-5.6
    image: registry.saas.hand-china.com/tools/mysql:5.6
    ports:
    - "3306:3306"
    env:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sakila
      user: root
      password: 1234
      countryId: 87
      customerId: 130

   java:
     container_name: Exam1
     image: registry.saas.hand-china.com/hap-cloud/base:latest
